# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on:  macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up dependencies
        run: brew install bison mingw-w64

      - name: Fetch wine source
        run: git clone --depth=1 https://github.com/wine-mirror/wine.git
        
      # Have configure as it's own step incase things change
      - name: Configure wine64
        run: |
          cd $GITHUB_WORKSPACE/wine
          ./configure --enable-win64 BISON=$(brew --prefix bison)/bin/bison MACOSX_DEPLOYMENT_TARGET=10.14
      
      # Build wine64 as it's own step
      - name: Build wine64
        run: |
          cd $GITHUB_WORKSPACE/wine
          make -j$(sysctl -n hw.ncpu 2>/dev/null)
