name: homebrew

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  wine-devel:
    runs-on:  macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew install --cask xquartz
          brew install  bison \
                        faudio \
                        gphoto2 \
                        gst-plugins-base \
                        little-cms2 \
                        mingw-w64 \
                        molten-vk \
                        mpg123

      - name: Add bison & krb5 to $PATH
        run: |
          set -eu
          echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH
          echo "$(brew --prefix krb5)/bin" >> $GITHUB_PATH

      - name: Fetch wine source
        run: git clone --depth=1 https://github.com/wine-mirror/wine.git

      - name: Configure wine64
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.14"
        run: |
          cd $GITHUB_WORKSPACE/wine
          ./configure   --enable-win64 \
                        --without-alsa \
                        --without-capi \
                        --without-dbus \
                        --without-inotify \
                        --without-oss \
                        --without-pulse \
                        --without-udev \
                        --without-v4l2 \
                        --x-include=/opt/X11/include \
                        --x-lib=/opt/X11/lib

      - name: Build wine64
        run: |
          cd $GITHUB_WORKSPACE/wine
          make -j$(sysctl -n hw.ncpu 2>/dev/null)

  wine-staging:
    runs-on:  macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew install --cask xquartz
          brew install  bison \
                        faudio \
                        gphoto2 \
                        gst-plugins-base \
                        little-cms2 \
                        mingw-w64 \
                        molten-vk \
                        mpg123

      - name: Add bison & krb5 to $PATH
        run: |
          set -eu
          echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH
          echo "$(brew --prefix krb5)/bin" >> $GITHUB_PATH

      - name: Fetch wine-staging source
        run: git clone --depth=1 https://github.com/wine-staging/wine-staging

      - name: Get upstream-commit
        run: |
          mkdir $GITHUB_WORKSPACE/wine
          cd wine
          git init
          git fetch https://github.com/wine-mirror/wine.git $($GITHUB_WORKSPACE/wine-staging/patches/patchinstall.sh --upstream-commit) --depth=1
          git checkout $($GITHUB_WORKSPACE/wine-staging/patches/patchinstall.sh --upstream-commit)

      - name: Apply Staging patches
        run: |
          $GITHUB_WORKSPACE/wine-staging/patches/patchinstall.sh DESTDIR=$GITHUB_WORKSPACE/wine

      - name: Configure wine64
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.14"
        run: |
          cd $GITHUB_WORKSPACE/wine
          ./configure   --enable-win64 \
                        --without-alsa \
                        --without-capi \
                        --without-dbus \
                        --without-inotify \
                        --without-oss \
                        --without-pulse \
                        --without-udev \
                        --without-v4l2 \
                        --x-include=/opt/X11/include \
                        --x-lib=/opt/X11/lib

      - name: Build wine64
        run: |
          cd $GITHUB_WORKSPACE/wine
          make -j$(sysctl -n hw.ncpu 2>/dev/null)
