name: homebrew

on:
  push:
    paths-ignore:
    - '.github/**'
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  wine-devel:
    runs-on:  macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew install  bison \
                        gstreamer \
                        mingw-w64 \
                        molten-vk

      - name: Add bison to $PATH
        run: |
          set -eu
          echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH

      - name: Fetch wine source
        run: git clone --depth=1 https://github.com/wine-mirror/wine.git

      - name: Configure wine64
        env:
          LDFLAGS: "-Wl,-headerpad_max_install_names -Wl,-rpath,/usr/local/lib"
          # Avoid weird linker errors with Xcode 10 and later
          MACOSX_DEPLOYMENT_TARGET: "10.14"
        run: |
          cd $GITHUB_WORKSPACE/wine
          ./configure   --enable-win64 \
                        --without-alsa \
                        --without-capi \
                        --without-dbus \
                        --without-inotify \
                        --without-oss \
                        --without-pulse \
                        --without-udev \
                        --without-v4l2

      - name: Build wine64
        run: |
          cd $GITHUB_WORKSPACE/wine
          make -j$(sysctl -n hw.ncpu 2>/dev/null)
