name: macports

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  wine-devel:
    runs-on:  macos-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install macports
        run: . $GITHUB_WORKSPACE/.github/workflows/bootstrap.sh
        
      - name: Determine list of changed ports
        run: |
          set -eu
          # Add getopt, mpbb and the MacPorts paths to $PATH for the subsequent
          # steps.
          echo "/opt/mports/bin" >> $GITHUB_PATH
          echo "${PWD}/mpbb" >> $GITHUB_PATH
          echo "/opt/local/bin" >> $GITHUB_PATH
          echo "/opt/local/sbin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
           sudo port selfupdate
           sudo port install bison

      - name: Fetch wine source
        run: git clone --depth=1 https://github.com/wine-mirror/wine.git

      - name: Configure wine64
        run: |
          cd $GITHUB_WORKSPACE/wine
          ./configure   --enable-win64 \
                        --without-pulse \
                        --without-v4l2 \
                        --without-oss \
                        MACOSX_DEPLOYMENT_TARGET=10.14

      - name: Build wine64
        run: |
          cd $GITHUB_WORKSPACE/wine
          make -j$(sysctl -n hw.ncpu 2>/dev/null)

  wine-staging:
    runs-on:  macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install macports
        run: . $GITHUB_WORKSPACE/.github/workflows/bootstrap.sh

      - name: Determine list of changed ports
        run: |
          set -eu
          # Add getopt, mpbb and the MacPorts paths to $PATH for the subsequent
          # steps.
          echo "/opt/mports/bin" >> $GITHUB_PATH
          echo "${PWD}/mpbb" >> $GITHUB_PATH
          echo "/opt/local/bin" >> $GITHUB_PATH
          echo "/opt/local/sbin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
           sudo port selfupdate
           sudo port install     autoconf \
                                 bison \
                                 faudio \
                                 gnutls \
                                 mingw-w64

      - name: Fetch wine-staging source
        run: git clone --depth=1 https://github.com/wine-staging/wine-staging

      - name: Grab winesource from staging
        run: |
          mkdir $GITHUB_WORKSPACE/wine
          cd wine
          git init
          git fetch https://github.com/wine-mirror/wine.git $($GITHUB_WORKSPACE/wine-staging/patches/patchinstall.sh --upstream-commit) --depth=1
          git checkout $($GITHUB_WORKSPACE/wine-staging/patches/patchinstall.sh --upstream-commit)

      - name: Apply Staging patches
        run: |
          $GITHUB_WORKSPACE/wine-staging/patches/patchinstall.sh DESTDIR=$GITHUB_WORKSPACE/wine

      - name: Configure wine64
        run: |
          cd $GITHUB_WORKSPACE/wine
          ./configure   --enable-win64 \
                        --without-pulse \
                        --without-v4l2 \
                        --without-oss \
                        MACOSX_DEPLOYMENT_TARGET=10.14

      - name: Build wine64
        run: |
          cd $GITHUB_WORKSPACE/wine
          make -j$(sysctl -n hw.ncpu 2>/dev/null)
